// scan.js — generate FIXES.md from @fix markers
const fs = require('fs');
const path = require('path');
const { listProtected } = require('./markers');

async function scan(root) {
  const regions = await listProtected(root);
  const out = path.join(root, 'FIXES.md');

  if (regions.length === 0) {
    fs.writeFileSync(out, '# Protected Fixes\n\n_No `@fix` markers found yet._\n');
    console.log('fixguard: 0 protected regions. Wrote FIXES.md');
    return;
  }

  // Group by tag
  const byTag = new Map();
  for (const r of regions) {
    if (!byTag.has(r.tag)) byTag.set(r.tag, []);
    byTag.get(r.tag).push(r);
  }

  let md = '# Protected Fixes\n\n';
  md += `> Auto-generated by [fixguard](https://github.com/) — do not edit by hand.\n`;
  md += `> ${regions.length} protected region(s) across ${new Set(regions.map(r => r.file)).size} file(s).\n\n`;
  md += `## How this works\n\n`;
  md += `Each entry below is a bug fix marked with \`@fix\` in source. Touching these lines\n`;
  md += `triggers \`fixguard check\` (run as a git pre-commit hook). Read the **reason** before\n`;
  md += `modifying — these are battle-scarred fixes that broke production at least once.\n\n`;

  for (const [tag, list] of [...byTag.entries()].sort()) {
    md += `## \`${tag}\`\n\n`;
    for (const r of list) {
      md += `- **${r.file}:${r.startLine}-${r.endLine}**`;
      if (r.reason) md += ` — ${r.reason}`;
      md += '\n';
    }
    md += '\n';
  }

  fs.writeFileSync(out, md);
  console.log(`fixguard: ${regions.length} protected region(s) → FIXES.md`);
}

module.exports = { scan };
